"""
PackAssist - Professional one-page "Pack Report" PDF generator (Pack Studio style).

Produces a single A4 sheet containing:
    - Header: part info (name, dims, weight) + PackAssist branding
    - Hero: large isometric render of the packed box
    - Metrics: clean grid of key numbers
    - Small multi-views: top / front / side
    - Cost summary (only when cost data is present)

Standalone: python pdf_generator.py [input.json] [output.pdf]
Requires:  fpdf2  (pip install fpdf2)
"""

import json
import os
import sys
from datetime import datetime

try:
    from fpdf import FPDF
except ImportError:  # pragma: no cover
    raise SystemExit("fpdf2 is required: pip install fpdf2")

VERSION = "v1.0.0"

# Accent / palette (Pack Studio style)
GREEN = (5, 150, 105)      # #059669
GREEN_LIGHT = (240, 253, 249)  # #f0fdf9
GREEN_PALE = (209, 250, 229)   # #d1fae5
DARK = (17, 24, 39)        # #111827
GRAY = (107, 114, 128)     # #6b7280
BORDER = (229, 231, 235)   # #e5e7eb
BG = (248, 250, 252)       # #f8fafc

STRINGS = {
    'ca': {
        'kicker': 'Informe d\'Empaquetatge',
        'weight': 'Pes',
        'pieceCount': 'Nombre de peces',
        'volumeUsage': 'Ús del volum',
        'boxDims': 'Caixa (mm)',
        'weightPerPiece': 'Pes / peça',
        'totalWeight': 'Pes total',
        'modeUsed': 'Mode',
        'modeFast': 'Planar',
        'modeBulk': 'A granel',
        'modeGpu': 'GPU',
        'topView': 'Vista Superior',
        'frontView': 'Vista Frontal',
        'sideView': 'Vista Lateral',
        'isometricView': 'Vista Isomètrica',
        'costTitle': 'Resum de costos',
        'boxCost': 'Cost caixa',
        'packagingCost': 'Embalatge',
        'freightCost': 'Transport',
        'costPerPart': 'Cost per peça',
        'generatedBy': 'Generat per PackAssist'
    },
    'en': {
        'kicker': 'Pack Report',
        'weight': 'Weight',
        'pieceCount': 'Piece count',
        'volumeUsage': 'Fill rate',
        'boxDims': 'Box (mm)',
        'weightPerPiece': 'Weight / piece',
        'totalWeight': 'Total weight',
        'modeUsed': 'Mode',
        'modeFast': 'Planar',
        'modeBulk': 'Bulk',
        'modeGpu': 'GPU',
        'topView': 'Top View',
        'frontView': 'Front View',
        'sideView': 'Side View',
        'isometricView': 'Isometric View',
        'costTitle': 'Cost summary',
        'boxCost': 'Box cost',
        'packagingCost': 'Packaging',
        'freightCost': 'Freight',
        'costPerPart': 'Cost per part',
        'generatedBy': 'Generated by PackAssist'
    }
}


def _find_unicode_font():
    """Return paths to regular + bold Unicode TTFs, or (None, None)."""
    candidates = [
        ("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
         "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"),
        ("/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
         "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"),
        ("C:\\Windows\\Fonts\\arial.ttf", "C:\\Windows\\Fonts\\arialbd.ttf"),
    ]
    for regular, bold in candidates:
        if os.path.exists(regular):
            return regular, (bold if os.path.exists(bold) else regular)
    return None, None


class PackReportPDF(FPDF):
    """Single-page Pack Report generator (Pack Studio style)."""

    def __init__(self, lang_code='ca'):
        super().__init__(format='A4', unit='mm')
        self.lang_code = lang_code if lang_code in STRINGS else 'ca'
        self.strs = STRINGS[self.lang_code]
        self.set_auto_page_break(auto=False)

        regular, bold = _find_unicode_font()
        if regular:
            self.add_font('Pack', '', regular)
            self.add_font('Pack', 'B', bold or regular)
            self.font_family = 'Pack'
        else:
            self.font_family = 'helvetica'

    # ── low-level helpers ───────────────────────────────────────
    def _font(self, style='', size=9):
        self.set_font(self.font_family, style, size)

    def _set_fill(self, rgb):
        self.set_fill_color(*rgb)

    def _set_text(self, rgb):
        self.set_text_color(*rgb)

    def _set_draw(self, rgb):
        self.set_draw_color(*rgb)

    def _rounded_rect(self, x, y, w, h, r=2, fill=None, line=None, line_width=0.3):
        if fill is not None:
            self._set_fill(fill)
        if line is not None:
            self._set_draw(line)
            self.set_line_width(line_width)
        else:
            self._set_draw(line or BORDER)
            self.set_line_width(line_width)
        self.rect(x, y, w, h, style='DF' if fill is not None else 'D')

    def _fit_image(self, path, x, y, box_w, box_h):
        """Place an image inside a box preserving aspect ratio. Returns (w, h, x, y)."""
        if not path or not os.path.exists(path):
            return None
        try:
            info = self.images[path]
            iw, ih = info['w'], info['h']
        except Exception:
            # fall back to a naive square assumption
            iw, ih = box_w, box_h
        scale = min(box_w / iw, box_h / ih)
        w, h = iw * scale, ih * scale
        return w, h, x + (box_w - w) / 2, y + (box_h - h) / 2

    def _draw_header(self, name, dims_text, weight_text, date_str):
        # Left: kicker + title + subtitle
        self._set_text(GREEN)
        self._font('B', 7)
        self.set_xy(9, 9)
        self.cell(120, 4, self.strs['kicker'].upper(), ln=0)
        self._set_text(DARK)
        self._font('B', 17)
        self.set_xy(9, 14)
        self.cell(135, 8, self._clip(name, 46), ln=0)
        self._set_text(GRAY)
        self._font('', 9)
        self.set_xy(9, 23)
        self.cell(140, 4, f"{dims_text} · {self.strs['weight']} {weight_text} kg")

        # Right: PackAssist branding
        self._set_text(GREEN)
        self._font('B', 13)
        self.set_xy(120, 10)
        self.cell(81, 6, "PackAssist", ln=0, align='R')
        self._set_text(GRAY)
        self._font('', 8)
        self.set_xy(120, 17)
        self.cell(81, 4, f"{VERSION} · {date_str}", ln=0, align='R')

        # Header bottom border
        self._set_draw(DARK)
        self.set_line_width(1.0)
        self.line(9, 29, 201, 29)

    def _draw_metric(self, x, y, w, h, value, label, highlight=False, size=13):
        self._rounded_rect(x, y, w, h, r=2,
                           fill=(GREEN_LIGHT if highlight else None),
                           line=(GREEN if highlight else BORDER), line_width=0.4)
        if highlight:
            self._set_text(GREEN)
        else:
            self._set_text(DARK)
        self._font('B', size)
        self.set_xy(x + 2.5, y + 3)
        self.multi_cell(w - 5, size + 1.2, self._clip(str(value), 14), align='L')
        self._set_text(GRAY)
        self._font('B', 7)
        self.set_xy(x + 2.5, y + h - 7)
        self.multi_cell(w - 5, 3.2, label, align='L')

    def _draw_hero(self, image_path, caption):
        # Frame
        self._rounded_rect(9, 32, 112, 112, r=3, fill=BG, line=BORDER)
        fit = self._fit_image(image_path, 13, 36, 104, 96)
        if fit:
            w, h, x, y = fit
            self.image(image_path, x, y, w=w, h=h)
        else:
            self._set_text(GRAY)
            self._font('', 9)
            self.set_xy(13, 70)
            self.cell(104, 4, caption, align='C')
        # Caption
        self._set_text(GRAY)
        self._font('B', 7)
        self.set_xy(9, 132)
        self.cell(112, 4, caption, align='C')

    def _draw_small_views(self, views):
        """views: dict {top, front, side} -> image paths."""
        y0, h = 160, 42
        x_start, col_w, gap = 9, 60, 6
        labels = [self.strs['topView'], self.strs['frontView'], self.strs['sideView']]
        for i, (key, label) in enumerate(zip(['top', 'front', 'side'], labels)):
            x = x_start + i * (col_w + gap)
            self._rounded_rect(x, y0, col_w, h, r=2, fill=BG, line=BORDER)
            fit = self._fit_image(views.get(key), x + 4, y0 + 2, col_w - 8, h - 12)
            if fit:
                w, ih, ix, iy = fit
                self.image(views.get(key), ix, iy, w=w, h=ih)
            self._set_text(GRAY)
            self._font('B', 7)
            self.set_xy(x, y0 + h - 7)
            self.cell(col_w, 4, label, align='C')

    def _draw_cost(self, cost):
        if not cost:
            return
        y0, h = 206, 30
        # Section box
        self._rounded_rect(9, y0, 192, h + 9, r=2.5, fill=GREEN_LIGHT, line=GREEN, line_width=0.6)
        self._set_text(GREEN)
        self._font('B', 8)
        self.set_xy(11, y0 + 2)
        self.cell(60, 4, self.strs['costTitle'].upper(), ln=0)

        col_w, gap, x0 = 45, 4, 11
        cols = [
            (self.strs['boxCost'], cost.get('box_cost')),
            (self.strs['packagingCost'], cost.get('packaging_cost')),
            (self.strs['freightCost'], cost.get('freight_cost')),
            (self.strs['costPerPart'], cost.get('cost_per_part')),
        ]
        for i, (label, value) in enumerate(cols):
            x = x0 + i * (col_w + gap)
            highlight = (i == 3)
            self._rounded_rect(x, y0 + 8, col_w, h - 8, r=2,
                               fill=(GREEN if highlight else None),
                               line=(GREEN if highlight else GREEN_PALE), line_width=0.4)
            v = self._fmt_euro(value)
            if highlight:
                self._set_text((255, 255, 255))
            else:
                self._set_text(GREEN)
            self._font('B', 11)
            self.set_xy(x + 2.5, y0 + 11)
            self.multi_cell(col_w - 5, 5, self._clip(v, 10), align='L')
            if highlight:
                self._set_text((255, 255, 255))
            else:
                self._set_text(GRAY)
            self._font('B', 6.5)
            self.set_xy(x + 2.5, y0 + h - 6)
            self.multi_cell(col_w - 5, 3, label, align='L')

    def _draw_footer(self, date_str):
        self._set_draw(BORDER)
        self.set_line_width(0.4)
        self.line(9, 280, 201, 280)
        self._set_text(GRAY)
        self._font('B', 7)
        self.set_xy(9, 283)
        self.cell(100, 4, self.strs['generatedBy'])
        self._set_text(GREEN)
        self.set_xy(140, 283)
        self.cell(61, 4, f"PackAssist {VERSION} · {date_str}", align='R')

    # ── value formatting ───────────────────────────────────────
    def _fmt_dim(self, v):
        try:
            return f"{float(v):g}"
        except (TypeError, ValueError):
            return str(v)

    def _fmt_euro(self, value):
        if value is None or value == '':
            return '—'
        try:
            v = float(value)
        except (TypeError, ValueError):
            return '—'
        return f"{v:,.2f} €".replace(",", " ")

    def _clip(self, text, max_chars):
        text = str(text)
        return text if len(text) <= max_chars else text[: max_chars - 1] + "…"

    # ── main entry point ───────────────────────────────────────
    def generate_pack_report(self, data, output_path):
        self.add_page()
        lang = data.get('lang_code', self.lang_code)
        if lang not in STRINGS:
            lang = 'ca'
        self.lang_code = lang
        self.strs = STRINGS[lang]

        piece_dims = data.get('piece_dims', [0, 0, 0])
        box_dims = data.get('box_dims', [0, 0, 0])
        name = data.get('name') or data.get('part_name') or 'Part'
        mode = data.get('mode', 'bulk')
        mode_label = {
            'fast': self.strs['modeFast'],
            'bulk': self.strs['modeBulk'],
            'gpu': self.strs['modeGpu'],
        }.get(mode, mode)

        piece_count = data.get('piece_count', 0)
        piece_weight = data.get('piece_weight', 0)
        total_weight = data.get('total_weight')
        if total_weight is None:
            total_weight = piece_count * piece_weight
        volume_usage = data.get('volume_usage')
        if volume_usage is None:
            pv = data.get('piece_volume_cm3', 0)
            bv = data.get('box_volume_cm3', 0)
            volume_usage = (piece_count * pv / bv * 100) if bv else 0

        date_str = data.get('date') or datetime.now().strftime('%d/%m/%Y')
        dims_text = " × ".join(self._fmt_dim(d) for d in piece_dims[:3])

        self._draw_header(name, dims_text, f"{piece_weight}", date_str)

        # Metrics grid (2 columns x 3 rows)
        bd = box_dims[:3]
        if len(set(bd)) == 1 and len(bd) == 3:
            box_dims_str = f"{bd[0]}³"
        else:
            box_dims_str = "×".join(str(d) for d in bd)
        metrics = [
            (f"{piece_count}", self.strs['pieceCount'], 13),
            (f"{volume_usage:.1f}%", self.strs['volumeUsage'], 13),
            (box_dims_str, self.strs['boxDims'], 10),
            (f"{piece_weight:g}", self.strs['weightPerPiece'], 13),
            (f"{total_weight:.2f} kg", self.strs['totalWeight'], 13),
            (mode_label, self.strs['modeUsed'], 13),
        ]
        x0, y0, col_w, row_h, gap = 124, 32, 37, 37, 4
        for i, (value, label, size) in enumerate(metrics[:6]):
            col = i % 2
            row = i // 2
            x = x0 + col * (col_w + gap)
            y = y0 + row * (row_h + gap)
            self._draw_metric(x, y, col_w, row_h, value, label,
                              highlight=(row == 2 and col == 1), size=size)

        # Hero
        images = data.get('images') or {}
        hero_path = data.get('hero_image') or images.get('hero')
        self._draw_hero(hero_path, self.strs['isometricView'])

        # Small views
        self._draw_small_views({
            'top': data.get('top_image') or images.get('top'),
            'front': data.get('front_image') or images.get('front'),
            'side': data.get('side_image') or images.get('side'),
        })

        # Cost (optional)
        self._draw_cost(data.get('cost'))

        # Footer
        self._draw_footer(date_str)

        self.output(output_path)


def _resolve_path(p, base_dir):
    if not p:
        return None
    if os.path.isabs(p):
        return p if os.path.exists(p) else None
    return os.path.join(base_dir, p) if os.path.exists(os.path.join(base_dir, p)) else p


def main():
    if len(sys.argv) > 1 and os.path.exists(sys.argv[1]):
        with open(sys.argv[1], encoding='utf-8') as fh:
            data = json.load(fh)
        base_dir = os.path.dirname(os.path.abspath(sys.argv[1]))
        data.setdefault('images', {})
        for key in ('hero_image', 'top_image', 'front_image', 'side_image'):
            data[key] = _resolve_path(data.get(key), base_dir)
        for key in ('hero', 'top', 'front', 'side'):
            if key in data.get('images', {}):
                data['images'][key] = _resolve_path(data['images'][key], base_dir)
    else:
        data = {
            'name': 'ANCHOR BRACKET APR1',
            'part_name': 'ANCHOR BRACKET APR1',
            'piece_dims': [50, 67, 50],
            'box_dims': [160, 160, 160],
            'piece_count': 79,
            'piece_weight': 0.104,
            'total_weight': 8.216,
            'volume_usage': 11.5,
            'mode': 'fast',
            'lang_code': 'ca',
            'cost': {
                'box_cost': 0.85,
                'packaging_cost': 0.22,
                'freight_cost': 1.20,
                'cost_per_part': 0.0287,
            },
        }

    output_path = sys.argv[2] if len(sys.argv) > 2 else 'test_pack_report.pdf'
    pdf = PackReportPDF(lang_code=data.get('lang_code', 'ca'))
    pdf.generate_pack_report(data, output_path)
    print(f"Pack report generated: {output_path}")


if __name__ == "__main__":
    main()
